In [ ]:
faqs= """
I am writing to inform you that I will be attending the Occupational Safety Conference 2023, which will be held from January 15 to January 17 in Islamabad, Pakistan. This conference is organized by the International Association of Occupational Health and Safety (IAOHS), and it will focus on the latest trends, challenges, and best practices in the field of occupational safety.

The conference will feature keynote speeches, panel discussions, workshops, and networking sessions with experts and practitioners from various industries and sectors. Some of the topics that will be covered include:

- Occupational safety standards and regulations
- Risk assessment and management
- Ergonomics and human factors
- Workplace wellness and mental health
- Emergency preparedness and response
- Occupational safety education and training

I believe that attending this conference will be beneficial for my professional development and for our organization's performance and reputation. I will learn new skills and knowledge that I can apply to my current and future projects, and I will also have the opportunity to exchange ideas and insights with other professionals in the field.

I will be away from the office for three days, from January 15 to January 17. I have already completed all my pending tasks and delegated my responsibilities to my colleagues. I will also be available via email and phone in case of any urgent matters.

I appreciate your support and understanding for my attendance at this conference. I will share with you the key takeaways and outcomes of the conference when I return.

We are writing to update you on the status of the software project that we are developing for you. We regret to inform you that we have encountered some unforeseen technical challenges that have caused delays in our progress.

The main issue that we are facing is related to the integration of the third-party API that we are using to provide some of the core functionalities of the software. The API has recently changed its specifications and documentation, and we have to modify our code and test cases accordingly. This has resulted in a significant amount of rework and debugging, which has taken longer than expected.

We apologize for any inconvenience and frustration that this may have caused you. We understand that this project is important for your business and that you have a tight deadline to meet. We are doing our best to resolve the issue as soon as possible and deliver a high-quality product that meets your requirements and expectations.

We appreciate your patience and cooperation in this matter. We will keep you informed of our progress and notify you of the revised delivery date as soon as we have a clear estimate. Please feel free to contact us if you have any questions or concerns.

I am writing to bring to your attention an issue of academic integrity that has occurred in our department. Recently, I have discovered that some of the students in our graduate program have been engaging in plagiarism and cheating in their assignments and exams. This is a serious violation of the university's code of conduct and ethics, and it undermines the quality and reputation of our academic program.

As a fellow faculty member, I am concerned about the impact of this issue on our students, colleagues, and institution. I believe that we need to take immediate and appropriate actions to address this issue and prevent it from happening again. Here are some of the possible solutions that I propose:

i.Implement a strict policy of academic honesty and integrity, and communicate it clearly to all students and faculty members. The policy should include the definition, examples, and consequences of academic dishonesty, as well as the procedures for reporting and resolving cases of misconduct.
ii.Use plagiarism detection software and other tools to check the originality and authenticity of students' work. The software and tools should be applied consistently and fairly to all students and assignments, and the results should be verified and documented.
iii.Provide more guidance and support to students on how to conduct proper research, cite sources, and avoid plagiarism. This can be done through workshops, tutorials, online resources, and feedback. The guidance and support should also emphasize the importance and value of academic integrity and ethical behavior.
iv.Foster a culture of academic excellence and integrity among students and faculty members. This can be done by recognizing and rewarding students who demonstrate academic honesty and integrity, and by encouraging collaboration and peer review among students and faculty members.

I hope that you will consider these suggestions and take the necessary steps to resolve this issue. I am willing to cooperate and assist you in any way that I can. Please let me know if you have any questions or concerns.
"""

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer= Tokenizer()

In [ ]:
tokenizer.fit_on_texts([faqs])

In [ ]:
tokenizer.word_index

{'e': 1,
 'a': 2,
 't': 3,
 'i': 4,
 'n': 5,
 'o': 6,
 's': 7,
 'r': 8,
 'd': 9,
 'c': 10,
 'l': 11,
 'h': 12,
 'u': 13,
 'p': 14,
 'm': 15,
 'f': 16,
 'y': 17,
 'g': 18,
 'and': 19,
 'w': 20,
 'v': 21,
 'b': 22,
 'the': 23,
 'to': 24,
 'of': 25,
 'k': 26,
 'that': 27,
 'we': 28,
 'you': 29,
 'will': 30,
 'this': 31,
 'in': 32,
 'have': 33,
 'be': 34,
 'our': 35,
 'for': 36,
 'students': 37,
 'j': 38,
 'x': 39,
 'as': 40,
 'academic': 41,
 'q': 42,
 'conference': 43,
 'my': 44,
 'are': 45,
 'issue': 46,
 'z': 47,
 'occupational': 48,
 'safety': 49,
 'from': 50,
 'some': 51,
 'any': 52,
 'your': 53,
 'integrity': 54,
 '1': 55,
 'am': 56,
 'january': 57,
 'is': 58,
 'it': 59,
 'on': 60,
 'can': 61,
 'software': 62,
 'has': 63,
 'faculty': 64,
 'should': 65,
 "'": 66,
 'writing': 67,
 'by': 68,
 'with': 69,
 'also': 70,
 'all': 71,
 'support': 72,
 'plagiarism': 73,
 'members': 74,
 '2': 75,
 '5': 76,
 '7': 77,
 'inform': 78,
 'attending': 79,
 'which': 80,
 '15': 81,
 '17': 82,
 'health'

In [ ]:
input_sequences=[]
for sentence in faqs.split("\n"):
 tokenized_sentence= tokenizer.texts_to_sequences([sentence])[0]

 for i in range(1,len(tokenized_sentence)):
  input_sequences.append(tokenized_sentence[:i+1])


In [ ]:
input_sequences

[[4, 56],
 [4, 56, 67],
 [4, 56, 67, 24],
 [4, 56, 67, 24, 78],
 [4, 56, 67, 24, 78, 29],
 [4, 56, 67, 24, 78, 29, 27],
 [4, 56, 67, 24, 78, 29, 27, 4],
 [4, 56, 67, 24, 78, 29, 27, 4, 30],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34, 79],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34, 79, 23],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34, 79, 23, 48],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34, 79, 23, 48, 49],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34, 79, 23, 48, 49, 43],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34, 79, 23, 48, 49, 43, 123],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34, 79, 23, 48, 49, 43, 123, 80],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34, 79, 23, 48, 49, 43, 123, 80, 30],
 [4, 56, 67, 24, 78, 29, 27, 4, 30, 34, 79, 23, 48, 49, 43, 123, 80, 30, 34],
 [4,
  56,
  67,
  24,
  78,
  29,
  27,
  4,
  30,
  34,
  79,
  23,
  48,
  49,
  43,
  123,
  80,
  30,
  34,
  124],
 [4,
  56,
  67,
  24,
  78,
  29,
  27,
  4,
  30,
  34,
  79,
  23,
  48,
  49,
  43,
  123,


In [ ]:
max_len=max([len(x) for x in input_sequences])

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
pad_input_sequence=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [ ]:
pad_input_sequence[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4, 56],
      dtype=int32)

In [ ]:
X=pad_input_sequence[:,:-1]
y=pad_input_sequence[:,-1]

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,   4],
       [  0,   0,   0, ...,   0,   4,  56],
       [  0,   0,   0, ...,   4,  56,  67],
       ...,
       [  0,   0,   0, ...,  29,  33,  52],
       [  0,   0,   0, ...,  33,  52, 108],
       [  0,   0,   0, ...,  52, 108, 109]], dtype=int32)

In [ ]:
y

array([ 56,  67,  24,  78,  29,  27,   4,  30,  34,  79,  23,  48,  49,
        43, 123,  80,  30,  34, 124,  50,  57,  81,  24,  57,  82,  32,
       125, 126,  31,  43,  58, 127,  68,  23, 128, 129,  25,  48,  83,
        19,  49, 130,  19,  59,  30, 131,  60,  23, 132, 133,  84,  19,
        85, 134,  32,  23,  86,  25,  48,  49,  43,  30, 135, 136, 137,
       138, 139,  87,  19, 140, 141,  69, 142,  19, 143,  50, 144, 145,
        19, 146,  51,  25,  23, 147,  27,  30,  34, 148,  88,  49, 149,
        19, 150, 152,  19, 153,  19, 155, 156, 158,  19, 159,  83, 161,
        19, 162,  49, 163,  19, 164,  89,  27,  79,  31,  43,  30,  34,
       165,  36,  44, 166, 167,  19,  36,  35, 168, 169,  19,  90,   4,
        30, 170, 171, 172,  19, 173,  27,   4,  61, 174,  24,  44, 175,
        19, 176, 177,  19,   4,  30,  70,  33,  23, 178,  24, 179, 180,
        19, 181,  69,  91, 182,  32,  23,  86,  30,  34, 183,  50,  23,
       184,  36, 185, 186,  50,  57,  81,  24,  57,  82,   4,  3

In [ ]:
X.shape

(768, 67)

In [ ]:
y.shape

(768,)

In [ ]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=len(tokenizer.word_index)+1)

In [ ]:
y.shape

(768, 378)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [ ]:
model= Sequential()
model.add(Embedding(378,100,input_length=max_len-1))
model.add(LSTM(150))
model.add(Dense(378,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 67, 100)           37800     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 378)               57078     
                                                                 
Total params: 245478 (958.90 KB)
Trainable params: 245478 (958.90 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X,y,epochs=100,validation_data=(X,y))

Epoch 1/100
24/24 [==============================] - 4s 164ms/step - loss: 5.1418 - accuracy: 0.0872 - val_loss: 5.0803 - val_accuracy: 0.0872
Epoch 2/100
24/24 [==============================] - 6s 248ms/step - loss: 5.1098 - accuracy: 0.0872 - val_loss: 5.0482 - val_accuracy: 0.0872
Epoch 3/100
24/24 [==============================] - 4s 168ms/step - loss: 5.0703 - accuracy: 0.0872 - val_loss: 4.9942 - val_accuracy: 0.0872
Epoch 4/100
24/24 [==============================] - 4s 164ms/step - loss: 5.0025 - accuracy: 0.0872 - val_loss: 4.9120 - val_accuracy: 0.0872
Epoch 5/100
24/24 [==============================] - 6s 244ms/step - loss: 4.8999 - accuracy: 0.0872 - val_loss: 4.7908 - val_accuracy: 0.0977
Epoch 6/100
24/24 [==============================] - 4s 164ms/step - loss: 4.7776 - accuracy: 0.1068 - val_loss: 4.6400 - val_accuracy: 0.1224
Epoch 7/100
24/24 [==============================] - 4s 165ms/step - loss: 4.6256 - accuracy: 0.1263 - val_loss: 4.4681 - val_accuracy: 0.1367

In [ ]:
import numpy as np

text='appreciate your support'
for i in range(10):
  #tokenizee
  token_text= tokenizer.texts_to_sequences([text])[0]
  #padding
  padded_token_text= pad_sequences([token_text],maxlen=max_len-1,padding='pre')
  #predict
  pos=np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text= text +" "+  word
      print(text)

1/1 [==============================] - 0s 32ms/step
appreciate your support and
1/1 [==============================] - 0s 31ms/step
appreciate your support and understanding
1/1 [==============================] - 0s 30ms/step
appreciate your support and understanding for
1/1 [==============================] - 0s 32ms/step
appreciate your support and understanding for my
1/1 [==============================] - 0s 31ms/step
appreciate your support and understanding for my attendance
1/1 [==============================] - 0s 40ms/step
appreciate your support and understanding for my attendance at
1/1 [==============================] - 0s 31ms/step
appreciate your support and understanding for my attendance at this
1/1 [==============================] - 0s 30ms/step
appreciate your support and understanding for my attendance at this conference
1/1 [==============================] - 0s 30ms/step
appreciate your support and understanding for my attendance at this conference i
1/1 [===========